replace biome format with prettier

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -1,7 +1,14 @@
 pre-commit:
   # parallel: true
   commands:
-    biome:
-      glob: "*.{js,ts,jsx,tsx,astro,svelte}"
-      run: bunx @biomejs/biome check --fix {staged_files}
+    prettier:
+      glob: "*.{js,ts,jsx,tsx,astro,svelte,md,mdx}"
+      run: bunx prettier {staged_files} --write
       stage_fixed: true
+    biome:
+      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
+      run: biome lint --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
+      stage_fixed: true
+    prevent-commit-on-main:
+      run: if [ "`git branch --show-current`" == 'main' ]; then echo 'Cannot make commit on main!'; exit 1; fi
+      
